# Version of docker-compose
version: '3'

services:
  commons-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=$SECRET_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      # HTTP
      - "traefik.http.routers.commons.entrypoints=http"
      - "traefik.http.routers.commons.rule=Host(`commons.bitsofether.com`)"
      - "traefik.http.routers.commons.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.commons-ssl.entrypoints=https"
      - "traefik.http.routers.commons-ssl.rule=Host(`commons.bitsofether.com`)"
      - "traefik.http.routers.commons-ssl.tls=true"
      - "traefik.http.routers.commons-ssl.tls.certresolver=myhttpchallenge"
    networks:
      - "web"
    ports:
      - "5000:5000"
    restart: always
networks:
  web:  
